<?php
/*
 *Implementation of hook_menu
*/
function enews_generator_menu(){
  $items['newsletter/generator'] = array(
    'title'            => 'Newsletter Generator',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('enews_generator_form'),
    'access arguments' => array('access content'),
    'type'            => MENU_CALLBACK,
  );
  return $items;
}
/**
 * Implementation of hook_theme().
 */
function enews_generator_theme() {
  return array(
    'enews_generator_form' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

function enews_generator_form(){
  // Load variable
  $names = array(
    'background' => t('Background color'),
    'base' => t('Base color'),
    'article-odd' => t('Article background 1'),
    'article-even' => t('Article background 2'),
    // special handle for text or link
    'link' => t('Link color'),
    'text' => t('Text color'),
    // extra1-x just search data-type
    'extra1' => t('Extra color !d', array('!d' => '1')),
  );
  $base = drupal_get_path('module', 'color');

  // Add Farbtastic color picker
  drupal_add_css('misc/farbtastic/farbtastic.css', 'module', 'all', FALSE);
  drupal_add_js('misc/farbtastic/farbtastic.js');

  // Add custom CSS/JS
//  drupal_add_css($base .'/color.css', 'module', 'all', FALSE);
//  drupal_add_js($base .'/color.js');
  drupal_add_css(drupal_get_path('module', 'enews_generator').'/enews_generator.css');
  drupal_add_js(drupal_get_path('module', 'enews_generator').'/enews_generator.js');
  $schemes = enews_generator_schemes($names);
  $schemes[''] = t('Custom');

  $form['scheme'] = array(
    '#type' => 'select',
    '#title' => t('Color set'),
    '#options' => $schemes,
    '#default_value' => '',
  );

  // Add palette fields
  $form['palette']['#tree'] = true;
  foreach ($names as $name => $translation) {
    $form['palette'][$name] = array(
      '#type' => 'textfield',
      '#title' => $translation,
      '#default_value' => $value,
      '#attributes' => array('class' => 'enews-palette'),
      '#size' => 8,
    );
  }
  return $form;
}
/**
 * Theme color and preview form.
 *
 * @ingroup themeable
 */
function theme_enews_generator_form($form) {
  // Include stylesheet
  $theme = $form['theme']['#value'];
  $info = $form['info']['#value'];
  $output = '';
  // Wrapper
  $output .= '<div id="enews-wrapper" class="clear-block">';

  // Color schemes
  $output .= drupal_render($form['scheme']);

  $output .= '<div class="clear-block">';

  // Palette
  $output .= '<div id="enews-palette">';
  foreach (element_children($form['palette']) as $name) {
    $output .= drupal_render($form['palette'][$name]);
  }
  $output .= '</div>';

  // Picker color box
  $output .= '<div id="enews-picker"></div>';

  // close enews-wrapper
  $output .= '<div align="center"><input type="button" id="enews-result" value="&raquo; 產生電子報" /></div>';
  $output .= '</div>';

  // Close wrapper
  $output .= '</div>';

  // Preview
  
  $output .= drupal_render($form);
  $output .= '<h2>'. t('Preview') .'</h2>';
  $output .= '<div id="enews-preview">';
  $output .= enews_generator_template_load('t1');
  $output .= '</div>';

  return $output;
}

/*
function enews_generator_validate($form, &$form_state){

}
function enews_generator_submit($form, &$form_state){

}
*/


function enews_generator_schemes($names){
/*
  if(module_exists('color_scheme')){
    $base = array(
      'test' => '6f5a00',
    );
    foreach($base as $k => $s){
      list($b, $f) = explode(',', $s);
      $c = enews_generator_scheme($names, $s);
      $schemes[$c] = $k;
    }
    return $schemes;
  }
*/
  $schemes = array(
    '#53A3AA,#F07404,#FFFFFF,#FFFFFF,#A81D06,#153204,#53A3AA' => 'Type1',
    '#C6344B,#B5A5A8,#EEE7E0,#EEE7E0,#777777,#C6344B,#A46E7C' => 'Type2',
    '#F0FDC1,#86A02D,#E5F4AD,#E5F4AD,#FF9100,#777777,#A9C457' => 'Type3',
  );
  return $schemes;
}

function enews_generator_scheme($names, $base_color, $fg_color, $inline = true){
/*
  $color = color_scheme_create($base_color, $fg_color);
  $cc = color_scheme_mix($base_color, 0.3, 135);
*/
  $rand = mt_rand(1,4);
  $rand2 = $rand == 4 ? $rand-1 : $rand+1;
  foreach($names as $k => $v){
    switch($k){
      case 'base':
        $names[$k] = $base_color;
        break;
      case 'background':
        $names[$k] = $color->bg['-5'];
        break;
      case 'article-odd':
      case 'article-even':
        $names[$k] = $color->bg['+'.$rand2];
        break;
      case 'link':
        $names[$k] = $color->fg['-'.$rand];
        break;
      case 'text':
        $names[$k] = $color->fg[0];
        break;
      case 'extra':
        $names[$k] = $color->bg['-5'];
        break;
      default:
        $names[$k] = $color->fg['+'.$rand];
    }
  }
  foreach($names as $k => $v){
    $names[$k] = '#'.$v;
  }
  if($inline){
    return implode(',', $names);
  }
  return $names;
}

function enews_generator_palette($schemes, $names){
  $rand = mt_rand(1, count($schemes));
  foreach($schemes as $s => $n){
    $i++;
    if($i == $rand){
      $value = explode(',', $s);
      break;
    }
  }
  $key = array_keys($names);
  return array_combine($key, $value);
}

function enews_generator_template_load($name){
  $path = drupal_get_path('module', 'enews_generator');
  $html = file_get_contents($path.'/templates/'.$name.'.inc');
  $html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');
  $css = file_get_contents($path.'/templates/'.$name.'.css');
  module_load_include('inc', 'enews_generator', 'css_to_inline_styles');
  $inline = new CSSToInlineStyles($html, $css);
  $inline->setEncoding('UTF-8');
  $html = $inline->convert();
  $html = mb_convert_encoding($html, 'UTF-8', 'HTML-ENTITIES');
  $html = preg_replace('/<\!DOC[^>]+>/', '', $html);
  $html = preg_replace('/<\/?html>/', '', $html);
  $html = preg_replace('/<\/?body>/', '', $html);
  return $html; 
}
