<?php

/**
 * Implementation of hook_menu
 */
function enews_generator_menu(){
  $items['newsletter/generator'] = array(
    'title'            => 'newsletter generator',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('enews_generator_form'),
    'access arguments' => array('access content'),
    'type'             => MENU_CALLBACK,
  );
  return $items;
}


/**
 * Implementation of hook_theme
 */
function enews_generator_theme() {
  return array(
    'enews_generator_form' => array(
      'arguments' => array('form' => NULL),
    ),
  );
}

/**
 * Form callback of drupal_get_form from menu
 */
function enews_generator_form(&$form_state){
  // Get templates we provide
  $templates = enews_generator_schemes($names);
  $posibile_template = $form_state['post']['scheme'] ? $form_state['post']['scheme'] : arg(2);

  // step 2 - pick color
  if(array_key_exists($posibile_template, $templates)){
    // Load variable for color setting. Each element is a ´textfield´ Form
    $names = array(
      'background' => t('Background color'),
      'base' => t('Base color'),
      'article-odd' => t('Article background 1'),
      'article-even' => t('Article background 2'),

      // special handle for text or link
      'link' => t('Link color'),
      'text' => t('Text color'),

      // extra1-x just search data-type
      'extra1' => t('Extra color !d', array('!d' => '1')),
    );

    // Add Farbtastic color picker
    drupal_add_css('misc/farbtastic/farbtastic.css', 'module', 'all', FALSE);
    drupal_add_js('misc/farbtastic/farbtastic.js');

    // Add custom CSS/JS
    drupal_add_css(drupal_get_path('module', 'enews_generator').'/enews_generator.css');
    drupal_add_js(drupal_get_path('module', 'enews_generator').'/enews_generator.js');

    // Form ´textfield´ : Add palette fields
    $form['palette']['#tree'] = true;
    foreach ($names as $name => $translation) {
      $form['palette'][$name] = array(
        '#type' => 'textfield',
        '#title' => $translation,
        '#default_value' => $value,
        '#attributes' => array('class' => 'enews-palette'),
        '#size' => 8,
      );
    }
  }
  // step 1 - select template
  else{
    $form['scheme'] = array(
      '#type' => 'select',
      //'#value' => t('template'),
      '#title' => t('Template'),
      '#options' => $templates,
      '#default_value' => '',
    );

    $form['choose'] = array(
      '#type' => 'submit',
      '#value' => t('Submit'),
      '#default_value' => '',
    );

    $form['element'] = array(
      '#type' => 'value',
      '#value' => isset($form_state['values']['scheme']) ? $form_state['values']['scheme'] : FALSE,
    );
  }
  return $form;
}
/**
 * callback after submit a form
 */
function enews_generator_form_submit($form, &$form_state){
  // Set rebuild to TRUE or form will not appear  ~jinmou
  $form_state['rebuild'] = TRUE;
}

/**
 * theme callback of form
 */
function theme_enews_generator_form($form) {
  $template = $form['#post']['scheme'] ? $form['#post']['scheme'] : arg(2);
  if ($template) {
    $output = '';

    // Wrapper
    $output .= '<div id="enews-wrapper" class="clear-block">';

    // Color schemes
    $output .= '<div class="clear-block">';

     // Palette
    $output .= '<div id="enews-palette">';
    foreach (element_children($form['palette']) as $name) {
      $output .= drupal_render($form['palette'][$name]);
    }
    $output .= '</div>';

    // Picker color box
    $output .= '<div id="enews-picker"></div>';

    // close enews-wrapper
    $output .= '<div align="center"><input type="button" id="enews-result" value="&raquo; 產生電子報" /></div>';
    $output .= '</div>';

    // Close wrapper
    $output .= '</div>';

    // Preview
    $output .= '<h2>'. t('Preview') .'</h2>';
    $output .= '<div id="enews-preview">';
    $output .= enews_generator_template_load($template);
    $output .= '</div>';
   }
  return $output;
}


/**
 * Template helper function
 *
 * scan directory to find out tpl.php
 */
function enews_generator_schemes($names){
  $path = drupal_get_path('module', 'enews_generator').'/templates';
  $files = file_scan_directory($path, '.tpl.php',  array('.', '..', 'CVS'), NULL, TRUE, 'name');
  foreach($files as $tpl => $file){
    $idx = rtrim($tpl, '.tpl');
    $info = drupal_parse_info_file($file->filename);
    // dpm($info['category']);
    $schemes[$idx] = $info['name'];
  }

  return $schemes;
}

/**
 * Template load helper function
 *
 * embed css into html to support modern mailbox
 */
function enews_generator_template_load($name){
  $path = drupal_get_path('module', 'enews_generator');
  $html = file_get_contents($path.'/templates/'.$name.'.inc');
  $html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');
  $css = file_get_contents($path.'/templates/'.$name.'.css');
  module_load_include('inc', 'enews_generator', 'css_to_inline_styles');
  $inline = new CSSToInlineStyles($html, $css); //class?
  $inline->setEncoding('UTF-8');
  $html = $inline->convert();
  $html = mb_convert_encoding($html, 'UTF-8', 'HTML-ENTITIES');
  $html = preg_replace('/<\!DOC[^>]+>/', '', $html);
  $html = preg_replace('/<\/?html>/', '', $html);
  $html = preg_replace('/<\/?body>/', '', $html);
  return $html;
}
