<div data-type="background" class="news-background" align="center" style="">
  <br />
  <br />
  <table border="0" cellpadding="0" cellspacing="0" width="600" style="width:600px;">
    <tbody>
    <tr>
    <td align="left" valign="top"><div data-type="base" class="news-base">
      <!-- top start here -->
      <div class="top-image">
        <img alt="" border="0" caption="" height="210" hspace="0" src="http://images.benchmarkemail.com/client171453/image535614.jpg" vspace="0" width="580" />
      </div>
      <div data-type="extra1" class="news-extra1">
        <strong><span style="">2012 年4月份電子報</span></strong>
      </div>
      <!-- top end here -->
      <!-- content start here -->
      <div data-type="header" class="news-header news-article">
        <h3 class="news-title">
          不要阿曼，只要阿力曼～鸞山森林博物館
        </h3>
        <div class="news-content">
          <blockquote>
            <p>
              不要阿曼(知名國際觀光旅館品牌)，只要阿力曼。阿力曼象徵的是 地方的能量，是可以自己詮釋自己、發展自己，樂於與來客分享生活經驗的從容和友善，這是別 人學不來的。找出自己的特色，走自己的路，這才是台灣發展觀光真正的最大優勢所在。<br />
              ～嚴長壽
            </p>
          </blockquote>
          <p>
            「森林是我們的銀行，用利息的觀念可以幫助我們永續經營。」阿力曼經常將這句話掛在嘴上，也希望將這個觀念深植在族人心中。他說重建森林的原貌和恢復傳統 文化可以帶給族人不同的好處，有形的幫助是觀光收入和創造族人就業機會，無形的幫助則是建立族人自信、促進各種文化交流&hellip;.</p>
          <p>
            一手催生森林博物館的館長「阿力曼」像台灣版鱷魚先生，從小在部落野放長大的阿力曼 對鸞山森林有一股難以言喻的感情，這裏有他和族人共同的回憶和情感，隨 著年歲漸長，外來的漢人將樹毒死擴大耕作面積，森林裏的樹木越來越少，大量噴灑農葯也造成動物逐漸消失，他的心裏非常難過卻不知如何阻止事態惡化，直到協 助東大劉教授進行當地榕樹調查和部落歷史文化保存時，開始與不同的環保、生態團體密切接觸，不僅提升了他的視野，也開啟了他保護森林的意識。(未完)</p>
          <p class="news-more">
            <a href="http://clt.bme1.net/c/l?u=BBF8B3&amp;e=16601B&amp;c=29DBD&amp;t=1&amp;email=qTCSHUofE1FzCUyl43EZnbf1pq7sJmAjapcheFTfYj0%3D" style="color: #369;text-decoration: none;" target="_blank">閱讀全文</a>
          </p>
        </div>
      </div>
      <div data-type="article-odd" class="news-article news-article-odd">
        <h3 class="news-title">
          多良木工坊漂流木工作營
        </h3>
        <div class="news-content">
          <img align="right" alt="" border="0" caption="" height="200" hspace="0" src="http://images.benchmarkemail.com/client171453/image534498.jpg" style="padding: 0 0 10px 10px;" vspace="0" width="200" />
          <p>
            多良木工坊(現名向陽薪傳木工坊)座落於台東太麻里鄉最南端的多良部落，其所在地原 是廢校多年的大溪國小多良分校，前方是一片深邃寬廣的太平洋海岸，下方 則是擁有「台灣最美麗的火車站」之稱的多良火車站，雖已廢站多年，仍吸引許多鐵道迷及背包客循線而上欣賞這片蔚藍的無敵美景。2011年一月，公益平台與 多良木工坊共同舉辦漂流木工作營，邀請複合式媒材藝術家許偉斌與曹世妹老師，以漂流木結合金屬質材的方式，透過實作與經驗分享，精進在地木造工作者傢具製 作技術；今年二月份基金會再度邀請二位老師至多良木工坊授課，以永續發展為訴求，為多良木工坊建構一個發展觀光的經營藍圖。
          </p>
          <p>
            為期四周的工作營，許偉斌老師帶領五名工班師傅改造木工坊的整體空間場域，除了將教 室改造為咖啡廳，讓遊客有一個舒適的休憩空間享用簡單的輕食飲品，並完 成一個呈現工坊作品的展示空間，讓遊客得以體驗多良部落的文化產業技藝。 許偉斌與曹世妹老師更運用漂流木廢材製作一系列的時鐘與鏡子等生活商品打樣，希望工班師傅們從實做中學習再創造，進而為多良的木造工藝研究注入更多在地特 色。下次您到多良時，別忘了探訪這個由廢棄小學所改造的木工坊。
          </p>
        </div>
      </div>
      <div data-type="article-even" class="news-article news-article-even">
        <h3 class="news-title">
          猶如初春發嫩芽的均一中小學
        </h3>
        <div class="news-content">
          <img align="right" alt="" border="0" caption="" height="200" hspace="0" src="http://images.benchmarkemail.com/client171453/image534500.jpg" style="padding: 0 0 10px 10px;" vspace="0" width="200" />
          <p>
            為了更加了解花東偏鄉小學學生的學習狀況，均一創新學習研發團隊在鄭漢文校長的指導 下，花費二個多月時間，親自探訪了33所花東偏鄉學校，其中還包括離島 地區的蘭嶼及綠島。研發團隊透過面對面一一向校長、老師以及學生們描繪未來均一中小學以重視啟發式教學、雙語學習環境以及生活品格教育的學習目標後，終獲 得百餘位七年級學生就學申請文件，101學年度七年級，公益平台將保留三分之一以上名額，以提供全額或部分獎助學金的方式，讓居住花東地區具學習潛能或藝 術天賦但經濟弱勢的優秀學生就讀，以培養花東偏鄉未來人才。</p>
        </div>
      </div>
      <!-- content end here -->
      <div align="center" style="font-size: 13px; padding: 10px 0;">
        <a href="http://twitter.com" style="color: #336699;font-weight: normal;text-decoration: underline;">跟隨Twitter</a>&nbsp;| <a href="http://www.facebook.com" style="color: #336699;font-weight: normal;text-decoration: underline;">加入Facebook粉絲團</a>&nbsp;| <a href="{action.forward}" style="color: #336699;font-weight: normal;text-decoration: underline;">轉寄本訊息</a>
      </div>
    </div><!-- news-base -->
    </td>
    </tr>
    </tbody>
  </table>
  <br />
  <br />
</div>

