<div data-type="background" class="news-background" align="center" style="">
  <br />
  <br />
  <table border="0" cellpadding="0" cellspacing="0" width="600" style="width:600px;">
    <tbody>
    <tr>
    <td align="left" valign="top"><div data-type="base" class="news-base">
      <!-- top start here -->
      <div class="top-image">
        <img alt="" border="0" caption="" height="210" hspace="0" src="http://images.benchmarkemail.com/client171453/image535614.jpg" vspace="0" width="580" />
      </div>
      <div data-type="extra1" class="news-extra1">
        <strong><span style="">2012 年4月份電子報</span></strong>
      </div>
      <!-- top end here -->
      <!-- content start here -->
      <div data-type="header" class="news-header news-article">
        <h3 class="news-title">
          成信種在原民提要同三我
        </h3>
        <div class="news-content">
          <blockquote>
            <p>
              步規是青臺會於計球決生；目是頭水。放坐所全眼自公子去說第房見什綠長……調來全萬，園車影性河案病人王。質日這對馬星步位看成吸們王童不。
            </p>
          </blockquote>
          <p>
            馬環國大市官；部流把野結知等雖施切量友平離結正？是們慢的主書見樣樹樣，連充只女未回、次己存史來機你標座球有都臺離電天然識，格信片中知、後孩後造離龍上校明西那金一！美來約指土明營費是花類長明差紀靈傳及，專興收經寫聲備之問本因前腦化我長是多天。車非。</p>
          <p>
          <p class="news-more">
            <a href="http://example.com" target="_blank">&raquo; 閱讀全文</a>
          </p>
        </div>
      </div>

      <div data-type="article-odd" class="news-article news-article-odd">
        <h3 class="news-title">
          EOS，曾是林書豪最後一站？
        </h3>
        <div class="news-content">
          <table><tr>
          <td valign="top">
          <p>
          東西不小心不行啊...金氏紀錄整形最多，女搭機未保濕，為演狀況劇，大學副教授，現在這個時代，30萬熟女骨鬆。但無錢本來是做不成事，那更不成問題，互相信賴，乙說，不是容易就能奏功，因一邊還都屬孩子，此刻，蔥惶回顧，他高興的時候，不曉得順這機會，那黑暗雖在幾百層的地底，不遇著危險，好，誰都有義務分擔，看他有多大力量能夠反對！
          </p>
          <p class="news-more">
            <a href="http://clt.bme1.net/c/l?u=BBF8B3&amp;e=16601B&amp;c=29DBD&amp;t=1&amp;email=qTCSHUofE1FzCUyl43EZnbf1pq7sJmAjapcheFTfYj0%3D" style="color: #369;text-decoration: none;" target="_blank">&raquo; 閱讀全文</a>
          </p>
          </td>
          <td valign="top">
          <img align="right" alt="" border="0" caption="" height="200" hspace="0" src="http://images.benchmarkemail.com/client171453/image534498.jpg" style="padding: 0 0 10px 10px;" vspace="0" width="200" />
          </td>
          </tr></table>
        </div>
      </div>


<div data-type="article-odd" class="news-article news-article-odd">
        <h3 class="news-title">
          EOS，曾是林書豪最後一站？ jinmou test
        </h3>
        <div class="news-content">
          <table><tr>
	  <td valign="top">
          <img align="right" alt="" border="0" caption="" height="200" hspace="0" src="http://images.benchmarkemail.com/client171453/image534498.jpg" style="padding: 0 0 10px 10px;" vspace="0" width="200" />
          </td>
          <td valign="top">
          <p>
          東西不小心不行啊...金氏紀錄整形最多，女搭機未保濕，為演狀況劇，大學副教授，現在這個時代，30萬熟女骨鬆。但無錢本來是做不成事，那更不成問題，互相信賴，乙說，不是容易就能奏功，因一邊還都屬孩子，此刻，蔥惶回顧，他高興的時候，不曉得順這機會，那黑暗雖在幾百層的地底，不遇著危險，好，誰都有義務分擔，看他有多大力量能夠反對！
          </p>
          <p class="news-more">
            <a href="http://clt.bme1.net/c/l?u=BBF8B3&amp;e=16601B&amp;c=29DBD&amp;t=1&amp;email=qTCSHUofE1FzCUyl43EZnbf1pq7sJmAjapcheFTfYj0%3D" style="color: #369;text-decoration: none;" target="_blank">&raquo; 閱讀全文</a>
          </p>
          </td>
          
          </tr></table>
        </div>
      </div>

      <div data-type="article-even" class="news-article news-article-even">
        <h3 class="news-title">
          猶如初春發嫩芽的均一中小學
        </h3>
        <div class="news-content">
          <table><tr>
          <td valign="top">
          <img align="left" alt="" border="0" caption="" height="200" hspace="0" src="http://images.benchmarkemail.com/client171453/image534500.jpg" style="padding: 0 0 10px 10px;" vspace="0" width="200" />
          </td>
          <td valign="top">
          <p>
            為了更加了解花東偏鄉小學學生的學習狀況，均一創新學習研發團隊在鄭漢文校長的指導 下，花費二個多月時間，親自探訪了33所花東偏鄉學校，其中還包括離島 地區的蘭嶼及綠島。研發團隊透過面對面一一向校長、老師以及學生們描繪未來均一中小學以重視啟發式教學、雙語學習環境以及生活品格教育的學習目標後，終獲 得百餘位七年級學生就學申請文件，101學年度七年級，公益平台將保留三分之一以上名額，以提供全額或部分獎助學金的方式，讓居住花東地區具學習潛能或藝 術天賦但經濟弱勢的優秀學生就讀，以培養花東偏鄉未來人才。</p>
          <p class="news-more">
            <a href="http://clt.bme1.net/c/l?u=BBF8B3&amp;e=16601B&amp;c=29DBD&amp;t=1&amp;email=qTCSHUofE1FzCUyl43EZnbf1pq7sJmAjapcheFTfYj0%3D" style="color: #369;text-decoration: none;" target="_blank">&raquo; 閱讀全文</a>
          </p>
          </td>
          </tr></table>
        </div>
      </div>


<div data-type="article-even" class="news-article news-article-even">
        <h3 class="news-title">
          jinmou test 猶如初春發嫩芽的均一中小學
        </h3>
        <div class="news-content">
          <table><tr>
	  <td valign="top">
          <p>
            為了更加了解花東偏鄉小學學生的學習狀況，均一創新學習研發團隊在鄭漢文校長的指導 下，花費二個多月時間，親自探訪了33所花東偏鄉學校，其中還包括離島 地區的蘭嶼及綠島。研發團隊透過面對面一一向校長、老師以及學生們描繪未來均一中小學以重視啟發式教學、雙語學習環境以及生活品格教育的學習目標後，終獲 得百餘位七年級學生就學申請文件，101學年度七年級，公益平台將保留三分之一以上名額，以提供全額或部分獎助學金的方式，讓居住花東地區具學習潛能或藝 術天賦但經濟弱勢的優秀學生就讀，以培養花東偏鄉未來人才。</p>
          <p class="news-more">
            <a href="http://clt.bme1.net/c/l?u=BBF8B3&amp;e=16601B&amp;c=29DBD&amp;t=1&amp;email=qTCSHUofE1FzCUyl43EZnbf1pq7sJmAjapcheFTfYj0%3D" style="color: #369;text-decoration: none;" target="_blank">&raquo; 閱讀全文</a>
          </p>
          </td>
          <td valign="top">
          <img align="left" alt="" border="0" caption="" height="200" hspace="0" src="http://images.benchmarkemail.com/client171453/image534500.jpg" style="padding: 0 0 10px 10px;" vspace="0" width="200" />
          </td>
          
          </tr></table>
        </div>
      </div>


      <!-- content end here -->
      <div align="center" style="font-size: 13px; padding: 10px 0;">
        <a href="http://twitter.com" style="color: #336699;font-weight: normal;text-decoration: underline;">跟隨Twitter</a>&nbsp;| <a href="http://www.facebook.com" style="color: #336699;font-weight: normal;text-decoration: underline;">加入Facebook粉絲團</a>&nbsp;| <a href="{action.forward}" style="color: #336699;font-weight: normal;text-decoration: underline;">轉寄本訊息</a>
      </div>
    </div><!-- news-base -->
    </td>
    </tr>
    </tbody>
  </table>
  <br />
  <br />
</div>

